# Vendored release toolkit; change the toolkit source, then render again.
# ruff: noqa
# mypy: ignore-errors
# pylint: skip-file
# fmt: off
"""Reject ambiguous workflows and mutable generated action references."""

import importlib.util
import json
import shutil
import tempfile
import unittest
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location(
    "workflow_contracts", ROOT / "scripts/workflow_contracts.py"
)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("Cannot load workflow contract checks")
CONTRACTS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(CONTRACTS)
SHA = "a" * 40
MARKER = (
    "# Generated by venus-os-ci-toolkit/scripts/install_release.py; edit .release-policy.json.\n"
)


class WorkflowYAMLTests(unittest.TestCase):
    """Exercise real parsing and the generator/consumer boundary."""

    def test_duplicate_top_level_and_nested_keys_are_rejected(self):
        for source in ("jobs: {}\njobs: {}", "jobs:\n  test:\n    uses: one\n    uses: two"):
            with self.subTest(source=source), self.assertRaises(ValueError):
                yaml.load(source, Loader=CONTRACTS.UniqueKeyLoader)

    def test_yaml_trigger_keys_and_scalars_remain_strings(self):
        result = yaml.load("on: push\nvalue: true\n", Loader=CONTRACTS.UniqueKeyLoader)
        self.assertEqual(result, {"on": "push", "value": "true"})

    def test_non_string_mapping_keys_are_rejected(self):
        with self.assertRaises(ValueError):
            yaml.load("? [one, two]\n: value", Loader=CONTRACTS.UniqueKeyLoader)

    def test_mutable_or_unknown_generated_actions_are_rejected(self):
        for reference, pins in (("actions/checkout@main", None), ("actions/checkout@" + SHA, {})):
            workflow = {"jobs": {"build": {"steps": [{"uses": reference}]}}}
            with self.subTest(reference=reference), self.assertRaises(ValueError):
                CONTRACTS.validate_workflow_pins("quality-gate.yml", workflow, pins)

    def test_local_steps_and_matching_manifest_are_supported(self):
        workflow = {
            "jobs": {
                "build": {
                    "steps": [
                        {"run": "true"},
                        {"uses": "./local"},
                        {"uses": "actions/checkout@" + SHA},
                    ]
                }
            }
        }
        CONTRACTS.validate_workflow_pins("quality-gate.yml", workflow, {"actions/checkout": SHA})

    def test_consumers_without_manifest_still_require_sha_and_marker(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            folder = root / ".github/workflows"
            folder.mkdir(parents=True)
            path = folder / "quality-gate.yml"
            workflow = {"jobs": {"build": {"steps": [{"uses": "actions/checkout@" + SHA}]}}}
            path.write_text(MARKER)
            CONTRACTS.validate_generator_pins(root, {path.name: workflow})
            path.write_text("# marker removed\n")
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {path.name: workflow})
            path.write_text(MARKER)
            workflow["jobs"]["build"]["steps"][0]["uses"] = "actions/checkout@main"
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {path.name: workflow})

    def test_canonical_generator_requires_its_manifest(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "scripts").mkdir()
            (root / "scripts/install_release.py").touch()
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {})

    def test_manifest_mismatch_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            folder = root / ".github/workflows"
            folder.mkdir(parents=True)
            (folder / "quality-gate.yml").write_text(MARKER)
            (root / ".github/action-pins.json").write_text(
                json.dumps([{"packageName": "actions/checkout", "digest": "b" * 40}])
            )
            workflow = {"jobs": {"build": {"steps": [{"uses": "actions/checkout@" + SHA}]}}}
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"quality-gate.yml": workflow})

    def test_reusable_workflows_require_immutable_matching_references(self):
        action = "owner/repo/.github/workflows/build.yml"
        for reference, pins in (
            (action + "@main", None),
            (action + "@v1", None),
            (action + "@" + SHA, {}),
            (action + "@" + SHA, {action: "b" * 40}),
        ):
            workflow = {"jobs": {"build": {"uses": reference}}}
            with self.subTest(reference=reference, pins=pins), self.assertRaises(ValueError):
                CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, pins)
        workflow = {"jobs": {"build": {"uses": action + "@" + SHA}}}
        CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, {action: SHA})
        CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, None)
        workflow["jobs"]["build"]["uses"] = "./.github/workflows/build.yml"
        CONTRACTS.validate_workflow_pins("release-pipeline.yml", workflow, {})

    def test_non_generated_workflows_require_sha_without_manifest_membership(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / ".github").mkdir()
            (root / ".github/action-pins.json").write_text(
                json.dumps([{"packageName": "actions/checkout", "digest": SHA}])
            )
            workflow = {"jobs": {"build": {"steps": [{"uses": "owner/action@" + SHA}]}}}
            CONTRACTS.validate_generator_pins(root, {"ci.yml": workflow})
            workflow["jobs"]["build"]["steps"][0]["uses"] = "owner/action@main"
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"ci.yml": workflow})
            workflow = {"jobs": {"build": {"uses": "owner/repo/.github/workflows/build.yml@main"}}}
            with self.assertRaises(ValueError):
                CONTRACTS.validate_generator_pins(root, {"other.yml": workflow})


class WorkflowEntryTests(unittest.TestCase):
    """Exercise entry-point checks against a complete copy of current workflows."""

    def test_all_pr_event_forms_require_gate_membership(self):
        for event in ("pull_request", "pull_request_target"):
            for declaration in (event, "[" + event + "]", "\n  " + event + ": {}"):
                with self.subTest(event=event, declaration=declaration):
                    with tempfile.TemporaryDirectory() as directory:
                        root = Path(directory)
                        shutil.copytree(ROOT / ".github", root / ".github")
                        shutil.copyfile(ROOT / ".release-policy.json", root / ".release-policy.json")
                        workflow = root / ".github/workflows/outside.yml"
                        workflow.write_text(
                            "name: Outside validation\non: " + declaration + "\n"
                            "jobs:\n  check:\n    runs-on: ubuntu-latest\n"
                            "    timeout-minutes: 5\n    steps:\n      - run: true\n"
                        )
                        with self.assertRaisesRegex(ValueError, "outside.yml: PR validator is outside"):
                            CONTRACTS.validate(root)

    def test_existing_review_request_workflow_remains_allowed(self):
        CONTRACTS.validate(ROOT)


if __name__ == "__main__":
    unittest.main()
