#!/usr/bin/env python3
"""Check the CI entry point and CodeQL compatibility before expensive validation."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

COMMIT_SHA_PATTERN = r"[0-9a-f]{40}"
QUALITY_GATE = "quality-gate.yml"


class UniqueKeyLoader(yaml.BaseLoader):
    """Keep YAML scalars as strings and reject ambiguous mappings."""

    def construct_mapping(self, node, deep=False):
        mapping = {}
        for key_node, value_node in node.value:
            key = self.construct_object(key_node, deep=deep)
            if not isinstance(key, str) or key in mapping:
                raise ValueError(
                    f"Duplicate or non-string YAML key at {key_node.start_mark}"
                )
            mapping[key] = self.construct_object(value_node, deep=deep)
        return mapping


def codeql_pins(job):
    """Read just the analyzer action references from one job."""
    return {
        step["uses"].rsplit("@", 1)[-1]
        for step in job.get("steps", [])
        if re.match(
            r"github/codeql-action/(init|autobuild|analyze|upload-sarif)@",
            step.get("uses", ""),
        )
    }


def validate_codeql(workflows):
    """All CodeQL components in the repository share one immutable release."""
    repository_pins = set()
    for filename, workflow in workflows.items():
        for name, job in workflow.get("jobs", {}).items():
            pins = codeql_pins(job)
            if len(pins) > 1 or any(
                not re.fullmatch(COMMIT_SHA_PATTERN, pin) for pin in pins
            ):
                raise ValueError(
                    f"{filename}/{name}: CodeQL actions must share one full commit SHA"
                )
            repository_pins.update(pins)
    if len(repository_pins) > 1:
        raise ValueError(
            "CodeQL actions across workflows must share one full commit SHA"
        )


def validate_action_reference(filename, reference, pins):
    """Check one external action against immutable and canonical pins."""
    if not reference or reference.startswith("./"):
        return
    action, _, revision = reference.partition("@")
    if not re.fullmatch(COMMIT_SHA_PATTERN, revision):
        raise ValueError(f"{filename}: {action} must use a full commit SHA")
    if pins is not None and (action not in pins or revision != pins[action]):
        raise ValueError(f"{filename}: {action} differs from generator pins")


def validate_workflow_pins(filename, workflow, pins):
    """Require immutable actions and compare canonical generator pins when present."""
    for job in workflow.get("jobs", {}).values():
        references = [job.get("uses", "")] + [
            step.get("uses", "") for step in job.get("steps", [])
        ]
        for reference in references:
            validate_action_reference(filename, reference, pins)


def generator_pins(directory):
    """Load the canonical pin set, including an opt-in coverage workflow."""
    manifest = directory / ".github/action-pins.json"
    # Consumers vendor the generated scripts, not the generator or its manifest.
    # The canonical toolkit must retain the manifest consumed by its generator.
    if not manifest.exists() and (directory / "scripts/install_release.py").exists():
        raise ValueError("Missing generator action-pin manifest")
    pins = (
        None
        if not manifest.exists()
        else {
            pin["packageName"]: pin["digest"]
            for pin in json.loads(manifest.read_text())
        }
    )
    if pins is not None and any(
        not re.fullmatch(COMMIT_SHA_PATTERN, pin) for pin in pins.values()
    ):
        raise ValueError("Generator pins must be full commit SHAs")
    policy_path = directory / ".release-policy.json"
    coverage = (
        json.loads(policy_path.read_text()).get("coverage")
        if policy_path.exists()
        else None
    )
    if pins is not None and coverage:
        pins[
            "victron-venus/venus-os-ci-toolkit/.github/workflows/coverage-upload.yml"
        ] = coverage["toolkit_ref"]
    return pins


def validate_generator_pins(directory, workflows):
    """Validate generated consumers and the toolkit's canonical pin manifest."""
    pins = generator_pins(directory)
    for filename, workflow in workflows.items():
        if filename not in {QUALITY_GATE, "release-pipeline.yml"}:
            validate_workflow_pins(filename, workflow, None)
            continue
        source = (directory / ".github/workflows" / filename).read_text()
        if not source.startswith(
            "# Generated by venus-os-ci-toolkit/scripts/install_release.py;"
        ):
            raise ValueError(f"{filename}: missing generator marker")
        validate_workflow_pins(filename, workflow, pins)


def _callable_workflow(workflows, visited, filename, chain=()):
    """Traverse callable workflows, retaining cycle detection before visited pruning."""
    if filename in chain:
        raise ValueError(f"Recursive validation: {chain} -> {filename}")
    if filename in visited:
        return
    workflow = workflows[filename]
    triggers = workflow.get("on", {})
    if not isinstance(triggers, dict) or "workflow_call" not in triggers:
        raise ValueError(f"{filename}: missing workflow_call")
    if set(triggers) - {"workflow_call", "workflow_dispatch"}:
        raise ValueError(f"{filename}: validation must start through Quality gate")
    visited.add(filename)
    for name, job in workflow.get("jobs", {}).items():
        reference = job.get("uses", "")
        if reference.startswith("./.github/workflows/"):
            _callable_workflow(
                workflows, visited, reference.rsplit("/", 1)[-1], (*chain, filename)
            )
        elif "runs-on" in job and "timeout-minutes" not in job:
            raise ValueError(f"{filename}/{name}: an explicit timeout is required")


def validate_graph(workflows, validators):
    """Walk callable validators and enforce one orchestration entry point."""
    visited = set()

    for filename in validators:
        _callable_workflow(workflows, visited, filename)
    return visited


def validate_coverage_producer(producer, report, ref):
    """Keep a producer's exported artifact and shared pin aligned with policy."""
    name = "coverage-" + report["name"]
    if "uses" in producer:
        workflow = {"cobertura": "python-ci.yml", "go": "go-ci.yml"}.get(
            report["format"]
        )
        expected = (
            f"victron-venus/venus-os-ci-toolkit/.github/workflows/{workflow}@{ref}"
        )
        if (
            workflow is None
            or producer["uses"] != expected
            or producer.get("with", {}).get("coverage-artifact-name") != name
        ):
            raise ValueError("Coverage producer pin or artifact differs from policy")
        return
    step_id = "export_coverage_" + report["name"].replace("-", "_")
    exports = [step for step in producer.get("steps", []) if step.get("id") == step_id]
    if (
        len(exports) != 1
        or not re.fullmatch(
            r"actions/upload-artifact@" + COMMIT_SHA_PATTERN,
            exports[0].get("uses", ""),
        )
        or exports[0].get("with", {}).get("name") != name + "-${{ github.run_attempt }}"
        or exports[0].get("with", {}).get("path") != report["path"]
    ):
        raise ValueError("Coverage producer export differs from policy")


def validate_coverage_callers(policy, workflows, gate):
    """Validate the opt-in upload graph and return its expected remote reference."""
    coverage = policy.get("coverage")
    if not coverage:
        return set()
    ref = coverage["toolkit_ref"]
    if not isinstance(ref, str) or not re.fullmatch(COMMIT_SHA_PATTERN, ref):
        raise ValueError("Coverage toolkit_ref must be a full commit SHA")
    reference = (
        "victron-venus/venus-os-ci-toolkit/.github/workflows/coverage-upload.yml@" + ref
    )
    for report in coverage["reports"]:
        name = "coverage-" + report["name"]
        upload = gate.get(name, {})
        producer_index = policy["validation_workflows"].index(report["workflow"])
        if (
            upload.get("uses") != reference
            or upload.get("needs") != ["scope", f"check-{producer_index}"]
            or upload.get("permissions")
            != {"contents": "read", "actions": "read", "id-token": "write"}
            or upload.get("with")
            != {
                "artifact-name": name,
                "report-file": report["path"].rsplit("/", 1)[-1],
                "format": report["format"],
                "flags": report["name"],
                "required": str(report["required"]).lower(),
            }
        ):
            raise ValueError(
                "Coverage upload caller differs from its policy or producer dependency"
            )
        producer = workflows[report["workflow"]]["jobs"][report["job"]]
        validate_coverage_producer(producer, report, ref)
    return {reference}


def _workflow_events(workflow):
    """Normalize GitHub's scalar, sequence and mapping event declarations."""
    triggers = workflow.get("on", {})
    if isinstance(triggers, str):
        return {triggers}
    if isinstance(triggers, (dict, list)):
        return set(triggers)
    raise ValueError("Workflow event declaration must be a string, list or mapping")


def validate(directory: Path, *, actions_only=False) -> None:
    """Reject duplicate validation triggers, missing gate jobs and mixed CodeQL pins."""
    policy = json.loads((directory / ".release-policy.json").read_text())
    workflows = {
        # UniqueKeyLoader inherits BaseLoader: no Python object construction.
        path.name: yaml.load(path.read_text(), Loader=UniqueKeyLoader)  # nosec B506
        for path in (directory / ".github/workflows").glob("*.y*ml")
    }
    validate_codeql(workflows)
    validate_generator_pins(directory, workflows)
    if actions_only:
        return
    visited = validate_graph(workflows, policy["validation_workflows"])
    for filename, workflow in workflows.items():
        if (
            _workflow_events(workflow) & {"pull_request", "pull_request_target"}
            and filename not in visited
            and filename
            not in {
                QUALITY_GATE,
                "auto-approve.yml",
                "auto-merge.yml",
                "coderabbit-review.yml",
            }
        ):
            raise ValueError(f"{filename}: PR validator is outside the required gate")
    gate = workflows[QUALITY_GATE]["jobs"]
    expected = {
        f"./.github/workflows/{filename}" for filename in policy["validation_workflows"]
    }
    expected.update(validate_coverage_callers(policy, workflows, gate))
    actual = {job.get("uses") for job in gate.values() if "uses" in job}
    if actual != expected or set(gate["gate"].get("needs", [])) != set(gate) - {"gate"}:
        raise ValueError(
            "CI gate must require every configured validator and contract job"
        )
    if "workflow-contracts" not in gate:
        raise ValueError("CI gate must include its configuration contracts")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--actions-only", action="store_true")
    validate(Path.cwd(), actions_only=parser.parse_args().actions_only)
    print("CI entry point, timeouts and CodeQL pins are consistent.")
